[workspace]
members = ["clifford-core", "clifford-field", "experiment-core"]
default-members = ["clifford-core", "clifford-field", "experiment-core"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/MonumentalSystems/commutator-rs"
homepage = "https://commutator.science"

[profile.release]
lto = "thin"
codegen-units = 1

